services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    image: rebac-api
    environment:
      FLASK_ENV: production
    depends_on:
      - client   
    ports:
      - "5000:5000"
  client:
    build:
      context: client
      dockerfile: Dockerfile
    image: rebac-client
    ports:
      - "3000:80"
  