services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    image: rebac-api
  client:
    build:
      context: client
      dockerfile: Dockerfile
    image: rebac-client
    ports:
      - "3000:80"
  